apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  labels:
    app: krissi-pimpin-pimpire
type: Opaque
data:
  # Base64 encoded Gemini API key
  # Replace 'your_base64_encoded_api_key_here' with your actual base64 encoded API key
  # To encode: echo -n "your_api_key" | base64
  api-key: your_base64_encoded_api_key_here